name: Webkiosk Checker

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download previous content files
      uses: actions/download-artifact@v4
      with:
        name: stored-content
        path: .
      continue-on-error: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_ADDRESS: ${{ secrets.TO_ADDRESS }}
        ROLL_NUMBER: ${{ secrets.ROLL_NUMBER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: python app.py
    
    - name: Upload stored page contents
      uses: actions/upload-artifact@v4
      with:
        name: stored-content
        path: |
          content_*.txt